split end to end tests client/worker
aneoconsulting/ArmoniK.Extensions.Csharp pull request #103
Opened 2022-10-19 08:18 UTC by ddubuc

fix https://github.com/aneoconsulting/ArmoniK/issues/631

2022-10-19 17:59 UTC, aneojgurhem commented on Common/src/Common/Ext/EnumExt.cs
> +  /// <param name="value"></param>
The doc is missing here

2022-10-19 17:59 UTC, aneojgurhem commented on Common/src/Common/Ext/IEnumerableExt.cs
> +namespace System.Collections.Generic
This breaks the fact that git would have been able to tell that this file was moved

2022-10-20 08:12 UTC, alouvion-aneo approved these changes

2022-10-20 08:35 UTC, dbrasseur-aneo requested changes

2022-10-20 08:35 UTC, dbrasseur-aneo commented on Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Client/Program.cs
> +                            }
```suggestion
    var clientsContainers = args.Length > 0
```

2022-10-20 08:35 UTC, dbrasseur-aneo commented on Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Client/Tests/CheckGridServer/HeavyPayloadGridServerClient.cs
> +using ArmoniK.DevelopmentKit.Client.Unified.Services.Submitter;
So the test is not "GridServer" anymore then ? Time for a rename ?

2022-10-20 08:35 UTC, dbrasseur-aneo commented on Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Client/Tests/CheckUnifiedApi/SimpleUnifiedAPITestClient.cs
> +                                                      .Select(_ => ParamsHelper(90)),
Careful that it doesn't lengthen the test for too long. With the pod killing itself after a few retries

2022-10-20 08:35 UTC, dbrasseur-aneo commented on Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Worker/Tests/CheckGridServer/SimpleGridServerTest.cs
> +  public double[] RandomTaskError(double percentageOfFailure = 0.25)
```suggestion
  public double[] RandomTaskError(double percentageOfFailure = 25)
```

2022-10-20 08:35 UTC, dbrasseur-aneo commented on Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Worker/Tests/CheckUnifiedApi/SimpleUnfiedAPITest.cs
> +      throw new WorkerApiException("An expected failure in this random call");
It's not linked to a WorkerApi failure, but a worker side exception. Should change the exception type here

2022-10-20 08:36 UTC, dbrasseur-aneo commented on Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Worker/Tests/CheckGridServer/SimpleGridServerTest.cs
> +  public double[] RandomTaskError(double percentageOfFailure = 0.25)
You divide by 100 after

2022-10-20 09:01 UTC, dbrasseur-aneo requested changes

2022-10-21 14:26 UTC, dbrasseur-aneo approved these changes

2022-10-21 14:26 UTC, merged