Right license in .editorconfig
aneoconsulting/ArmoniK.Extensions.Csharp pull request #111
Opened 2022-11-02 10:56 UTC by lemaitre-aneo

2022-11-21 07:32 UTC, ddubuc requested changes

2022-11-21 07:32 UTC, ddubuc commented on .editorconfig
> +file_header_template = This file is part of the ArmoniK project\n\nCopyright (C) ANEO, 2022-$CURRENT_YEAR$. All rights reserved.\n  W. Kirschenmann   <wkirschenmann@aneo.fr>\n  J. Gurhem         <jgu
```suggestion
file_header_template = This file is part of the ArmoniK project\n\nCopyright (C) ANEO, 2022-$CURRENT_YEAR$. All rights reserved.\n  W. Kirschenmann   <wkirschenmann@aneo.fr>\n  J. Gurhem         <jgurhem@aneo.fr>\n  D. Dubuc          <ddubuc@aneo.fr>\n  L. Ziane Khodja   <lzianekhodja@aneo.fr>\n  F. Lemaitre       <flemaitre@aneo.fr>\n  S. Djebbar        <sdjebbar@aneo.fr>\n  J. Fonseca        <jfonseca@aneo.fr>\n  D. Brasseur       <dbrasseur@aneo.fr>\n  A. Louvion       <alouvion@aneo.fr>\n\nLicensed under the Apache License, Version 2.0 (the "License")\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an "AS IS" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License.\n
```

2022-11-21 07:32 UTC, ddubuc commented on .editorconfig
> +file_header_template = This file is part of the ArmoniK project\n\nCopyright (C) ANEO, 2022-$CURRENT_YEAR$. All rights reserved.\n  W. Kirschenmann   <wkirschenmann@aneo.fr>\n  J. Gurhem         <jgu
add Arnaud in Aurthor list

2023-02-13 13:22 UTC, ddubuc commented on .editorconfig
> +file_header_template = This file is part of the ArmoniK project\n\nCopyright (C) ANEO, 2022-$CURRENT_YEAR$. All rights reserved.\n  W. Kirschenmann   <wkirschenmann@aneo.fr>\n  J. Gurhem         <jgu
```suggestion
file_header_template = This file is part of the ArmoniK project\n\nCopyright (C) ANEO, 2022-$CURRENT_YEAR$. All rights reserved.\n\nLicensed under the Apache License, Version 2.0 (the "License")\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an "AS IS" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License.\n
```

2023-02-19 20:49 UTC, aneojgurhem commented
A PR that updates the files to incorporate these changes should also be done

2023-06-07 14:46 UTC, aneojgurhem approved these changes

2023-06-07 17:56 UTC, merged