ci: upload infra logs
aneoconsulting/ArmoniK.Extensions.Csharp pull request #195
Opened 2023-07-04 15:20 UTC by dbrasseur-aneo

2023-08-18 05:25 UTC, aneojgurhem approved these changes

2023-08-18 05:27 UTC, aneojgurhem requested changes

2023-08-18 05:27 UTC, aneojgurhem commented on .github/workflows/build.yml
> +          cp infrastructure/quick-deploy/localhost/all/generated/armonik-terraform.tfstate end2end/infra/tfstates
this copy does not work

2023-08-18 08:03 UTC, dbrasseur-aneo commented on .github/workflows/build.yml
> +          cp infrastructure/quick-deploy/localhost/all/generated/armonik-terraform.tfstate end2end/infra/tfstates
Yes this pr needs more work

2023-08-24 14:54 UTC, aneojgurhem approved these changes

2023-08-24 15:13 UTC, merged