Implements ArmoniK.Api V3 support
aneoconsulting/ArmoniK.Extensions.Csharp pull request #58
Opened 2022-08-18 14:36 UTC by dbrasseur-aneo

2022-08-19 13:54 UTC, aneojgurhem requested changes

2022-08-19 13:54 UTC, aneojgurhem commented on Client/src/ArmoniK.DevelopmentKit.Client.Common/Submitter/BaseClientSubmitter.cs
> +    /// <param name="client">The <code>Submitter.SubmitterClient</code> client to use for the result retrieval.</param>
Remove this line. This will fix some warnings

2022-08-19 13:54 UTC, aneojgurhem commented on Client/src/ArmoniK.DevelopmentKit.Client.Common/Submitter/BaseClientSubmitter.cs
> +                                               if (taskOutput.TypeCase == Output.TypeOneofCase.Ok && response != null)
👍

2022-08-19 13:54 UTC, aneojgurhem commented on WorkerApi/ArmoniK.DevelopmentKit.WorkerApi.Common/ArmoniK.DevelopmentKit.WorkerApi.Common.csproj
>     <ItemGroup Condition=" '$(TargetFramework)' == 'net472' Or '$(TargetFramework)' == 'net48' ">
Shoud we remove it ? WorkerApi is net6 only

2022-08-19 13:54 UTC, aneojgurhem commented on WorkerApi/ArmoniK.DevelopmentKit.WorkerApi/ArmoniK.DevelopmentKit.WorkerApi.csproj
>    <ItemGroup Condition=" '$(TargetFramework)' == 'net5.0' Or '$(TargetFramework)' == 'net6.0'">
not necessary

2022-08-19 13:54 UTC, aneojgurhem commented on WorkerApi/ArmoniK.DevelopmentKit.WorkerApi/Services/ComputerService.cs
> +      using var scopedLog = LoggerExt.BeginNamedScope(Logger,
sooooo ugly : it is an extension method of ILogger. Should work with Logger.BeginNamedScope

2022-08-19 14:26 UTC, aneojgurhem approved these changes

2022-08-22 08:19 UTC, ngruelaneo approved these changes

2022-08-22 08:21 UTC, merged