Revamp TaskResult of UnifiedAPI
aneoconsulting/ArmoniK.Extensions.Csharp pull request #93
Opened 2022-09-30 07:24 UTC by lemaitre-aneo

2022-09-30 09:16 UTC, aneojgurhem requested changes

2022-09-30 09:16 UTC, aneojgurhem commented on UnifiedApi/Client/Services/Submitter/Service.cs
> +              var result = ProtoSerializer.DeSerializeMessageObjectArray(byteResult);
Maybe distinguish between error from deserializing and handler execution ?

2022-09-30 09:16 UTC, aneojgurhem commented on UnifiedApi/Client/Services/Submitter/Service.cs
> +          Thread.Sleep(100);
Is this necessary ?

2023-01-03 08:17 UTC, ddubuc requested changes

2023-01-03 08:17 UTC, ddubuc commented on Client/src/Unified/Services/Submitter/Service.cs
> +                                                                CancellationToken.None)
No usage of CancellationResultTaskSource.Token instead of CancellationToker.None ?

2023-01-03 08:17 UTC, ddubuc commented on Client/src/Unified/Services/Submitter/Service.cs
> +                                 taskId);
Re-throw exception here. User process should stop here since they don't manage properly the exception

2023-01-03 08:17 UTC, ddubuc commented on Client/src/Unified/Services/Submitter/Service.cs
> +                             resultStatusData.TaskId);
Add specific Try catch to manage Handle error ?

2023-01-03 08:17 UTC, ddubuc commented on Client/src/Unified/Services/Submitter/Service.cs
> +              }
Add specific exception for GetTaskStatus Grpc Request and call HandleError with Connection error exception if an exception occurs

2023-01-03 08:17 UTC, ddubuc commented on Client/src/Unified/Services/Submitter/Service.cs
> +                                  waitInSeconds.Length)
is it waitInSeconds.Length - 1 instead ?

2023-08-18 15:29 UTC, aneojgurhem commented
@lemaitre-aneo do we continue or close ?

2023-08-21 14:20 UTC, lemaitre-aneo commented
> @lemaitre-aneo do we continue or close ?

I don't know. I still think the change is relevant, but there was a slow down introduced by this change and I don't know where. We could close it and re-open it if we have more insight.

2025-05-16 08:08 UTC, closed without merging